name: Build and Deploy from Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Rename public to docs
        run: mv ./public ./docs  # Renomme le dossier public en docs

      - name: Create .nojekyll file
        run: echo "" > docs/.nojekyll  # Place le fichier .nojekyll dans le bon répertoire

      - name: Commit built files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy site to GitHub Pages"
          git push
