name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # Inclure main si tu utilises cette branche également

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Create .nojekyll file
        run: echo "" > public/.nojekyll  # Désactive Jekyll pour GitHub Pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'  # Autorise le déploiement depuis master ou main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true  # Force la création d'une nouvelle branche gh-pages sans historique
