name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Utilise la branche main comme source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Create .nojekyll file
        run: echo "" > public/.nojekyll  # Désactive Jekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Mise à jour vers la version v4
        if: github.ref == 'refs/heads/main'  # Déploie depuis la branche main
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}  # Utilisation d'un Personal Access Token (PAT)
          publish_dir: ./public
          force_orphan: true  # Force la création d'une nouvelle branche gh-pages
          allow_empty_commit: true  # Autorise les commits vides
